### PR TITLE
Add DS Wizard as FAIR data management planning tool2

### PR DESCRIPTION
**Pull request by MarekSuchanek**
Hello,

I propose to add [Data Stewardship Wizard](https://ds-wizard.org) as one of the tools that your MOOC Module covers. It is an open-source tool for planning how to work with data during and after the research with respect to the FAIR principles which is in our opinion crucial part of "reproducible research". In case of need, we can provide additional materials and help to include it in the course...

Best regards,
Marek 😄

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]
LGTM

**Comment by jcolomb** [comment]
hey, thanks.
I will definitively check it (and compare that to the RDMO tool that is on my list for a year by now).

Since development happens on a different branch, I will keep this pull request open to deal with merge problems later on.

**Comment by MarekSuchanek** [comment]
No problem, feel free to edit it and/or switch the target branch as you need 😄

**Comment by jcolomb** [comment]
I did not know one could do that. here we are!

**Comment by jcolomb** [comment]
mixed it up, but made the change by hand now

**Pull request merged**
